### ISSUE TITLE
ThreadName enricher

### ISSUE THREAD

**Issue by StefanOssendorf** [serilog/serilog-enrichers-thread#10]
Hi,

would you mind an additional enricher which adds the thread name?

I would start with the implementation after merging #9 .

**Comment by nblumhardt** [comment]
Thanks @StefanOssendorf - sounds like a great addition. Merged the related PR 👍

**Comment by StefanOssendorf** [comment]
See #11

**Comment by StefanOssendorf** [comment]
#11 is merged so this can be closed 👍

**Comment by StefanOssendorf** [comment]
Hey @nblumhardt do you have any plans on creating v3.0.1 which includes this?
I want to use this at work and not as a local copy&paste solution :-)

**Comment by nblumhardt** [comment]
Thanks for the nudge! #12 is cooking now.....
