### ISSUE TITLE
Allow enriching with ThreadId on all threads except 1

### ISSUE THREAD

**Issue by DragoonAethis** [serilog/serilog-enrichers-thread#15]
In a lightly multithreaded application it might be useful to remove ThreadId=1 (or a configurable ID if needed) to decrease noise in logs and leave the IDs only for non-main threads.

**Comment by nblumhardt** [comment]
Thanks for the suggestion!

This turns out to be a fairly widely-applicable idea; it is probably best implemented separately from this library.

One angle might be `Enrich.With(new DefaultPropertyValueRemover("ThreadId", 1)`:

```csharp
class DefaultPropertyValueRemover : ILogEventEnricher
{
  readonly string _propertyName;
  readonly ScalarValue _targetValue;

  public DefaultPropertyValueRemover(string propertyName, object targetValue)
  {
    _propertyName = propertyName;
    _targetValue = new ScalarValue(targetValue);
  }

  public void Enrich(LogEvent le, ILogEventPropertyFactory _)
  {
    if (le.Properties.TryGetValue(_propertyName, out var val) &&
      _targetValue.Equals(val))
    {
      le.RemovePropertyIfPresent(_propertyName);
    }
  }
}
```

(Not compiled or tested :-))

Let me know if this looks to do the job!

Cheers,
Nick

**Comment by DragoonAethis** [comment]
Yup, it works, thanks :)

Here's a gist with a minimal practical example of this: https://gist.github.com/DragoonAethis/a4a82c88eb462c2f4e9b776c34ff6317

**Comment by DragoonAethis** [comment]
Not sure if you'd prefer me to close this issue or perhaps try having a go at creating a separate library with this? (I'm not 100% sure if I know what I'm doing, so it might get a bit rocky at first :P)

**Comment by nblumhardt** [comment]
Let's leave this as a pointer to the Gist and see how things turn out 👍  - thanks for posting the complete version!
